//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// REVIEWAREA.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_REVIEW_AREA_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_AUTO                 130
#define IDD_DIALOG_MANUAL               132
#define IDD_DIALOG_SETTING              134
#define IDD_DIALOG_MEASURE              136
#define IDD_DIALOG_MANUAL_ALIGN         138
#define IDD_DIALOG_RESULT               140
#define IDD_DIALOG_ALARM                142
#define IDB_BITMAP_LOGO                 146
#define IDR_MENU_MAIN                   149
#define IDR_TOOLBAR_MAIN                150
#define IDD_DIALOG_SETTING_STAGE        152
#define IDD_DIALOG_SETTING_INFO         154
#define IDD_DIALOG_SETTING_PARAM        156
#define IDD_DIALOG_SETTING_HIDDEN       158
#define IDD_DIALOG_COMPORT              160
#define IDB_BITMAP_GREEN_LED            164
#define IDB_BITMAP_GREEN_LED_2          165
#define IDB_BITMAP_LOGO_2               166
#define IDB_BITMAP_RED_LED              167
#define IDB_BITMAP_RED_LED_2            168
#define IDD_DIALOG_SETTING_PROCESS      171
#define IDD_DIALOG_SETTING_INSPECT      173
#define IDB_BITMAP_CAM_OFF              176
#define IDB_BITMAP_CAM_ON               177
#define IDD_DIALOG_HISTORY              180
#define IDD_DIALOG_POPUP                183
#define IDB_BITMAP_TAB_1                186
#define IDB_BITMAP_TAB_1_A              187
#define IDB_BITMAP_TAB_2                188
#define IDB_BITMAP_TAB_2_A              189
#define IDB_BITMAP_TAB_3                190
#define IDB_BITMAP_TAB_3_A              191
#define IDB_BITMAP_TAB_4                192
#define IDB_BITMAP_TAB_4_A              193
#define IDB_BITMAP_TAB_5                194
#define IDB_BITMAP_TAB_5_A              195
#define IDB_BITMAP_TAB_6                196
#define IDB_BITMAP_TAB_6_A              197
#define IDB_BITMAP_TAB_7                198
#define IDB_BITMAP_TAB_7_A              199
#define IDB_BITMAP_TAB_8                200
#define IDB_BITMAP_TAB_8_A              201
#define IDB_BITMAP_TAB_9                202
#define IDB_BITMAP_TAB_9_A              203
#define IDB_BITMAP_TAB_10               204
#define IDB_BITMAP_TAB_10_A             205
#define IDB_BITMAP_TAB_11               206
#define IDB_BITMAP_TAB_11_A             207
#define IDB_BITMAP_TAB_12               208
#define IDB_BITMAP_TAB_12_A             209
#define IDB_BITMAP_TAB_13               210
#define IDB_BITMAP_TAB_13_A             211
#define IDB_BITMAP_TAB_14               212
#define IDB_BITMAP_TAB_14_A             213
#define IDB_BITMAP_TAB_15               214
#define IDB_BITMAP_TAB_15_A             215
#define IDB_BITMAP_TAB_16               216
#define IDB_BITMAP_TAB_16_A             217
#define IDB_BITMAP_TAB_17               218
#define IDB_BITMAP_TAB_17_A             219
#define IDB_BITMAP_TAB_18               220
#define IDB_BITMAP_TAB_18_A             221
#define IDB_BITMAP_TAB_19               222
#define IDB_BITMAP_TAB_19_A             223
#define IDB_BITMAP_TAB_20               224
#define IDB_BITMAP_TAB_20_A             225
#define IDB_BITMAP_TAB_21               226
#define IDB_BITMAP_TAB_21_A             227
#define IDB_BITMAP_TAB_22               228
#define IDB_BITMAP_TAB_22_A             229
#define IDB_BITMAP_TAB_23               230
#define IDB_BITMAP_TAB_23_A             231
#define IDB_BITMAP_TAB_24               232
#define IDB_BITMAP_TAB_24_A             233
#define IDB_BITMAP_TAB_25               234
#define IDB_BITMAP_TAB_25_A             235
#define IDB_BITMAP_TAB_26               236
#define IDB_BITMAP_TAB_26_A             237
#define IDB_BITMAP_TAB_27               238
#define IDB_BITMAP_TAB_27_A             239
#define IDB_BITMAP_TAB_28               240
#define IDB_BITMAP_TAB_28_A             241
#define IDB_BITMAP_TAB_29               242
#define IDB_BITMAP_TAB_29_A             243
#define IDB_BITMAP_TAB_30               244
#define IDB_BITMAP_TAB_30_A             245
#define IDB_BITMAP_STAGE_OFF            248
#define IDB_BITMAP_STAGE_ON             249
#define IDD_DIALOG_LOADING              250
#define IDB_BITMAP_AF_OFF               252
#define IDB_BITMAP_AF_ON                253
#define IDB_BITMAP_LIGHT_OFF            254
#define IDB_BITMAP_LIGHT_ON             255
#define IDB_BITMAP_CIRCLE_OFF           256
#define IDB_BITMAP_CIRCLE_ON            257
#define IDB_BITMAP_EDGE_1_OFF           258
#define IDB_BITMAP_EDGE_1_ON            259
#define IDB_BITMAP_EDGE_2_OFF           260
#define IDB_BITMAP_EDGE_2_ON            261
#define IDB_BITMAP_LINE_OFF             262
#define IDB_BITMAP_LINE_ON              263
#define IDB_BITMAP_RECTANGLE_OFF        264
#define IDB_BITMAP_RECTANGLE_ON         265
#define IDI_ICON1                       266
#define IDI_ICON_WIA                    266
#define IDD_DIALOG_SYSTEM               268
#define IDB_BITMAP_YELLOW_LED           270
#define IDD_DIALOG_MANUAL_UPPER         271
#define IDD_DIALOG_MANUAL_SIDE          273
#define IDB_BITMAP_GRAPHIC_ON           275
#define IDB_BITMAP_GRAPHIC_OFF          276
#define IDD_DIALOG_CLAMP                277
#define IDC_PIC_UPPER_CAM               1000
#define IDC_PIC_SIDE_CAM                1001
#define IDC_PIC_UPPER_LIGHT             1002
#define IDC_PIC_SIDE_LIGHT              1003
#define IDC_PIC_UPPER_AF                1004
#define IDC_PIC_SIDE_AF                 1005
#define IDC_PIC_START                   1006
#define IDC_PIC_STOP                    1007
#define IDC_TAB_WINDOWS                 1008
#define IDC_PIC_STAGE_MAIN_X            1009
#define IDC_PIC_LOGIN                   1009
#define IDC_PIC_STAGE_MAIN_Y            1010
#define IDC_PIC_STAGE_SUB_X             1011
#define IDC_PIC_LOGO                    1012
#define IDC_BTN_UPPER_CAM               1013
#define IDC_BTN_SIDE_CAM                1014
#define IDC_BTN_ALL_CAM                 1015
#define IDC_BTN_MAIN_STAGE_X            1016
#define IDC_BTN_MAIN_STAGE_Y            1017
#define IDC_BTN_SUB_STAGE_X             1018
#define IDC_BTN_ALL_STAGE               1019
#define IDC_BTN_UPPER_LIGHT             1020
#define IDC_BTN_SIDE_LIGHT              1021
#define IDC_EDIT_UPPER_LIGHT            1022
#define IDC_EDIT_SIDE_LIGHT             1023
#define IDC_SLD_UPPER                   1024
#define IDC_SLD_SIDE                    1025
#define IDC_EDIT_UPPER_AF_STEP          1026
#define IDC_EDIT_SIDE_AF_STEP           1027
#define IDC_SPIN_UPPER_AF               1028
#define IDC_SPIN_SIDE_AF                1029
#define IDC_BTN_UPPER_AF                1030
#define IDC_PIC_UPPER                   1031
#define IDC_BTN_SIDE_AF                 1031
#define IDC_PIC_SIDE                    1032
#define IDC_SPIN_AF                     1032
#define IDC_BTN_START                   1033
#define IDC_BTN_STOP                    1034
#define IDC_BTN_RESET                   1035
#define IDC_BTN_MOVE_STOP               1035
#define IDC_BTN_LOG_RESET               1036
#define IDC_BTN_STAGE_MAIN_X_MOVE       1036
#define IDC_BTN_ORIGIN                  1036
#define IDC_EDIT_STAGE_MAIN_X_POS       1037
#define IDC_BTN_STAGE_MAIN_Y_MOVE       1037
#define IDC_EDIT_STAGE_MAIN_X_READY_POS 1038
#define IDC_BTN_STAGE_SUB_X_MOVE        1038
#define IDC_EDIT_STAGE_MAIN_X_PROCESS_POS 1039
#define IDC_EDIT_STAGE_MAIN_X_LIMIT_MIN 1040
#define IDC_EDIT_STAGE_MAIN_X_LIMIT_MAX 1041
#define IDC_EDIT_STAGE_MAIN_X_MANUAL_SPEED 1042
#define IDC_EDIT_STAGE_MAIN_X_PROCESS_SPEED 1043
#define IDC_EDIT_STAGE_MAIN_Y_POS       1044
#define IDC_EDIT_STAGE_MAIN_Y_READY_POS 1045
#define IDC_EDIT_STAGE_MAIN_Y_PROCESS_POS 1046
#define IDC_EDIT_STAGE_MAIN_Y_LIMIT_MIN 1047
#define IDC_EDIT_STAGE_MAIN_Y_LIMIT_MAX 1048
#define IDC_EDIT_STAGE_MAIN_Y_MANUAL_SPEED 1049
#define IDC_EDIT_STAGE_MAIN_Y_PROCESS_SPEED 1050
#define IDC_EDIT_STAGE_SUB_X_POS        1051
#define IDC_EDIT_STAGE_SUB_X_READY_POS  1052
#define IDC_EDIT_STAGE_SUB_X_PROCESS_POS 1053
#define IDC_EDIT_STAGE_SUB_X_ALIGN_OFFSET 1054
#define IDC_EDIT_STAGE_SUB_X_LIMIT_MIN  1055
#define IDC_EDIT_STAGE_SUB_X_LIMIT_MAX  1056
#define IDC_EDIT_STAGE_SUB_X_MANUAL_SPEED 1057
#define IDC_STATIC_STAGE_MAIN_X_POS     1058
#define IDC_STATIC_STAGE_MAIN_X_READY_POS 1059
#define IDC_STATIC_STAGE_MAIN_X_PROCESS_POS 1060
#define IDC_STATIC_STAGE_MAIN_X_LIMIT_MIN 1061
#define IDC_STATIC_STAGE_MAIN_X_LIMIT_MAX 1062
#define IDC_STATIC_STAGE_MAIN_X_MANUAL_SPEED 1063
#define IDC_STATIC_STAGE_MAIN_X_PROCESS_SPEED 1064
#define IDC_STATIC_STAGE_MAIN_Y_POS     1065
#define IDC_STATIC_STAGE_MAIN_Y_READY_POS 1066
#define IDC_STATIC_STAGE_MAIN_Y_PROCESS_POS 1067
#define IDC_STATIC_STAGE_MAIN_Y_LIMIT_MIN 1068
#define IDC_STATIC_STAGE_MAIN_Y_LIMIT_MAX 1069
#define IDC_STATIC_STAGE_MAIN_Y_MANUAL_SPEED 1070
#define IDC_STATIC_STAGE_MAIN_Y_PROCESS_SPEED 1071
#define IDC_STATIC_STAGE_SUB_X_POS      1072
#define IDC_STATIC_STAGE_SUB_X_READY_POS 1073
#define IDC_STATIC_STAGE_SUB_X_PROCESS_POS 1074
#define IDC_STATIC_STAGE_SUB_X_LIMIT_MIN 1075
#define IDC_STATIC_STAGE_SUB_X_LIMIT_MAX 1076
#define IDC_STATIC_STAGE_SUB_X_MANUAL_SPEED 1077
#define IDC_STATIC_STAGE_SUB_X_PROCESS_SPEED 1078
#define IDC_STATIC_STAGE_SUB_X_ALIGN_OFFSET 1079
#define IDC_EDIT_STAGE_SUB_X_PROCESS_SPEED 1080
#define IDC_EDIT_TAB_COUNT              1081
#define IDC_BTN_MANUAL_INSPECT          1081
#define IDC_EDIT_TAB_POINT              1082
#define IDC_EDIT_TAB_DIST               1083
#define IDC_STATIC_PROCESS_READY        1084
#define IDC_EDIT_TAB_INTERVAL           1084
#define IDC_PIC_PROCESS_READY           1085
#define IDC_EDIT_PREALIGN_MATCHING      1085
#define IDC_EDIT_TACKTIME_PROCESS       1086
#define IDC_EDIT_TABALIGN_MATCHING      1086
#define IDC_STATIC_PROCESS_PROCESS      1087
#define IDC_EDIT_PREALIGN_RANGE         1087
#define IDC_STATIC_PROCESS_PREALIGN     1088
#define IDC_EDIT_WIDTH                  1088
#define IDC_STATIC_PROCESS_TABALIGN     1089
#define IDC_EDIT_HEIGHT                 1089
#define IDC_STATIC_PROCESS_INSPECTION   1090
#define IDC_EDIT_WIDTH_RANGE            1090
#define IDC_STATIC_PROCESS_TAB          1090
#define IDC_STATIC_PROCESS_JUDGE        1091
#define IDC_EDIT_HEIGHT_RANGE           1091
#define IDC_STATIC_PROCESS_UNLOADING    1092
#define IDC_EDIT_MA_X_RANGE             1092
#define IDC_PIC_PROCESS_PROCESS         1093
#define IDC_EDIT_MA_Y                   1093
#define IDC_PIC_PROCESS_PREALIGN        1094
#define IDC_EDIT_MA_Y_RANGE             1094
#define IDC_PIC_PROCESS_TABALIGN        1095
#define IDC_EDIT_BINARY_UPPER           1095
#define IDC_EDIT_OFFSET                 1095
#define IDC_PIC_PROCESS_INSPECTION      1096
#define IDC_EDIT_BINARY_SIDE            1096
#define IDC_EDIT_UPPER_ALIGN_OFFSET     1096
#define IDC_PIC_PROCESS_JUDGE           1097
#define IDC_EDIT_BINARY_EDGE            1097
#define IDC_EDIT_SIDE_ALIGN_OFFSET      1097
#define IDC_PIC_PROCESS_UNLOADING       1098
#define IDC_EDIT_MORPHOLOGY_OPEN        1098
#define IDC_EDIT_SPACE                  1098
#define IDC_EDIT_TACKTIME_ALIGN         1099
#define IDC_EDIT_MORPHOLOGY_CLOSE       1099
#define IDC_EDIT_TACKTIME_INSPECTION    1100
#define IDC_EDIT_UPPER_CONTOUR          1100
#define IDC_EDIT_TACKTIME_JUDGE         1101
#define IDC_EDIT_SIDE_CONTOUR           1101
#define IDC_EDIT_TACKTIME_UNLOADING     1102
#define IDC_EDIT_UPPER_ROI_MIN          1102
#define IDC_LIST_MA                     1103
#define IDC_EDIT_UPPER_ROI_MAX          1103
#define IDC_LIST_MA_X                   1103
#define IDC_LIST_OS                     1104
#define IDC_EDIT_SIDE_ROI_MIN           1104
#define IDC_EDIT_LOG                    1105
#define IDC_EDIT_SIDE_ROI_MAX           1105
#define IDC_LIST_OTHER                  1106
#define IDC_EDIT_EDGE_ROI_MIN           1106
#define IDC_EDIT_TACKTIME_TOTAL         1107
#define IDC_EDIT_EDGE_ROI_MAX           1107
#define IDC_STATIC_TACKTIME_PROCESS     1108
#define IDC_EDIT_GANTRY_LIMIT_MIN       1108
#define IDC_STATIC_TACKTIME_ALIGN       1109
#define IDC_EDIT_GANTRY_LIMIT_MAX       1109
#define IDC_STATIC_STAGE_MAIN_X         1109
#define IDC_STATIC_TACKTIME_INSPECTION  1110
#define IDC_EDIT_AF_LIMIT               1110
#define IDC_STATIC_STAGE_MAIN_Y         1110
#define IDC_STATIC_TACKTIME_JUDGE       1111
#define IDC_STATIC_STAGE_SUB_X          1111
#define IDC_STATIC_TACKTIME_UNLOADING   1112
#define IDC_STATIC_CAMERA_1             1112
#define IDC_STATIC_TACKTIME_TOTAL       1113
#define IDC_BTN_RECIPE                  1113
#define IDC_STATIC_CAMERA_2             1113
#define IDC_PIC_PROCESS_PREALIGN_PASS   1114
#define IDC_BTN_MODIFY                  1114
#define IDC_STATIC_LIGHT_1              1114
#define IDC_LIST_MA_Y                   1114
#define IDC_PIC_PROCESS_TABALIGN_PASS   1115
#define IDC_BTN_APPLY                   1115
#define IDC_STATIC_LIGHT_2              1115
#define IDC_BTN_CANCEL                  1116
#define IDC_STATIC_AF_1                 1116
#define IDC_EDIT_LOAD_RECIPE            1117
#define IDC_STATIC_START                1117
#define IDC_STATIC_TAB_COUNT            1118
#define IDC_STATIC_STOP                 1118
#define IDC_BTN_SAVE                    1118
#define IDC_STATIC_TAB_POINT            1119
#define IDC_STATIC_AF_2                 1119
#define IDC_STATIC_TAB_DIST             1120
#define IDC_STATIC_TAB_INTERVAL         1121
#define IDC_STATIC_PREALIGN_MATCHING    1122
#define IDC_STATIC_TABALIGN_MATCHING    1123
#define IDC_STATIC_PREALIGN_RANGE       1124
#define IDC_STATIC_WIDTH                1125
#define IDC_STATIC_HEIGHT               1126
#define IDC_STATIC_WIDTH_RANGE          1127
#define IDC_STATIC_HEIGHT_RANGE         1128
#define IDC_STATIC_MA_X_RANGE           1129
#define IDC_STATIC_MA_Y                 1130
#define IDC_STATIC_MA_Y_RANGE           1131
#define IDC_STATIC_BINARY_UPPER         1132
#define IDC_STATIC_BINARY_SIDE          1133
#define IDC_STATIC_BINARY_EDGE          1134
#define IDC_STATIC_MORPHOLOGY_OPEN      1135
#define IDC_STATIC_MORPHOLOGY_CLOSE     1136
#define IDC_STATIC_UPPER_CONTOUR        1137
#define IDC_STATIC_SIDE_CONTOUR         1138
#define IDC_STATIC_UPPER_ROI_MIN        1139
#define IDC_STATIC_UPPER_ROI_MAX        1140
#define IDC_STATIC_SIDE_ROI_MIN         1141
#define IDC_STATIC_SIDE_ROI_MAX         1142
#define IDC_STATIC_EDGE_ROI_MIN         1143
#define IDC_STATIC_EDGE_ROI_MAX         1144
#define IDC_STATIC_GANTRY_LIMIT_MIN     1145
#define IDC_STATIC_GANTRY_LIMIT_MAX     1146
#define IDC_STATIC_AF_LIMIT             1147
#define IDC_BTN_PREALIGN_PASS           1148
#define IDC_BTN_LINE                    1149
#define IDC_BTN_TABALIGN_PASS           1149
#define IDC_BTN_RECTANGLE               1150
#define IDC_BTN_TAB_PASS                1150
#define IDC_BTN_CIRCLE                  1151
#define IDC_BTN_TAB_1                   1151
#define IDC_BTN_UPPER_MARK_REG          1152
#define IDC_BTN_TAB_2                   1152
#define IDC_BTN_UPPER_MARK_SAVE         1153
#define IDC_BTN_TAB_3                   1153
#define IDC_BTN_TAB_4                   1154
#define IDC_BTN_EDGE_1                  1154
#define IDC_BTN_TAB_5                   1155
#define IDC_BTN_EDGE_2                  1155
#define IDC_STATIC_STAGE_MAIN_X_COMMAND 1156
#define IDC_BTN_TAB_6                   1156
#define IDC_STATIC_STAGE_MAIN_X_REFERENCE 1157
#define IDC_BTN_TAB_7                   1157
#define IDC_STATIC_STAGE_MAIN_Y_REFERENCE 1158
#define IDC_BTN_TAB_8                   1158
#define IDC_STATIC_STAGE_MAIN_Y_COMMAND 1159
#define IDC_BTN_TAB_9                   1159
#define IDC_STATIC_STAGE_SUB_X_REFERENCE 1160
#define IDC_BTN_TAB_10                  1160
#define IDC_STATIC_STAGE_SUB_X_COMMAND  1161
#define IDC_BTN_TAB_11                  1161
#define IDC_STATIC_STAGE_MAIN_X_POSITION 1162
#define IDC_BTN_TAB_12                  1162
#define IDC_STATIC_STAGE_MAIN_Y_POSITION 1163
#define IDC_BTN_TAB_13                  1163
#define IDC_STATIC_STAGE_SUB_X_POSITION 1164
#define IDC_BTN_TAB_14                  1164
#define IDC_CHK_ABS_1                   1165
#define IDC_BTN_TAB_15                  1165
#define IDC_CHK_REL_1                   1166
#define IDC_BTN_TAB_16                  1166
#define IDC_CHK_ABS_2                   1167
#define IDC_BTN_TAB_17                  1167
#define IDC_CHK_REL_2                   1168
#define IDC_BTN_TAB_18                  1168
#define IDC_CHK_ABS_3                   1169
#define IDC_BTN_TAB_19                  1169
#define IDC_CHK_REL_3                   1170
#define IDC_BTN_TAB_20                  1170
#define IDC_EDIT_STAGE_MAIN_X_COMMAND   1171
#define IDC_BTN_TAB_21                  1171
#define IDC_EDIT_STAGE_MAIN_X_REFERENCE 1172
#define IDC_BTN_TAB_22                  1172
#define IDC_EDIT_STAGE_MAIN_X_POSITION  1173
#define IDC_BTN_TAB_23                  1173
#define IDC_EDIT_STAGE_MAIN_Y_COMMAND   1174
#define IDC_BTN_TAB_24                  1174
#define IDC_EDIT_STAGE_MAIN_Y_REFERENCE 1175
#define IDC_BTN_TAB_25                  1175
#define IDC_EDIT_STAGE_MAIN_Y_POSITION  1176
#define IDC_BTN_TAB_26                  1176
#define IDC_EDIT_STAGE_SUB_X_COMMAND    1177
#define IDC_BTN_TAB_27                  1177
#define IDC_EDIT_STAGE_SUB_X_REFERENCE  1178
#define IDC_BTN_TAB_28                  1178
#define IDC_EDIT_STAGE_SUB_X_POSITION   1179
#define IDC_BTN_TAB_29                  1179
#define IDC_CHK_CROSSLINE               1180
#define IDC_BTN_TAB_30                  1180
#define IDC_EDIT_UPPER_POSITION         1181
#define IDC_BTN_GRAPHIC                 1181
#define IDC_EDIT_SIDE_POSITION          1182
#define IDC_BTN_UPPER_MARK_REG2         1182
#define IDC_BTN_SIDE_MARK_REG           1182
#define IDC_CMB_UPPER_MARK              1183
#define IDC_CMB_SIDE_MARK               1184
#define IDC_PIC_UPPER_MARK              1185
#define IDC_BTN_UPPER_MARK_SAVE2        1186
#define IDC_BTN_SIDE_MARK_SAVE          1186
#define IDC_PIC_SIDE_MARK               1187
#define IDC_LIST_MEASURE                1188
#define IDC_CHK_TAB_1                   1189
#define IDC_STATIC_MORP_OPEN            1189
#define IDC_CHK_TAB_2                   1190
#define IDC_STATIC_DAY                  1190
#define IDC_PIC_UPPER_MARK2             1190
#define IDC_STATIC_MORP_CLOSE           1190
#define IDC_CHK_TAB_3                   1191
#define IDC_STATIC_TIME                 1191
#define IDC_LIST_RESULT                 1191
#define IDC_STATIC_BINARY               1191
#define IDC_CHK_TAB_4                   1192
#define IDC_STATIC_RECIPE               1192
#define IDC_STATIC_CONTOUR              1192
#define IDC_CHK_TAB_5                   1193
#define IDC_STATIC_LIST_RESULT          1193
#define IDC_STATIC_RECIPE_NAME          1193
#define IDC_CHK_TAB_6                   1194
#define IDC_STATIC_LIST_MA_X            1194
#define IDC_CHK_TAB_7                   1195
#define IDC_STATIC_LIST_OS              1195
#define IDC_CHK_TAB_8                   1196
#define IDC_STATIC_LIST_OTHER           1196
#define IDC_CHK_TAB_9                   1197
#define IDC_STATIC_LIST_MA_Y            1197
#define IDC_CHK_TAB_10                  1198
#define IDC_CHK_TAB_11                  1199
#define IDC_CHK_TAB_12                  1200
#define IDC_CHK_TAB_13                  1201
#define IDC_CHK_TAB_14                  1202
#define IDC_CHK_TAB_15                  1203
#define IDC_TAB_SETTING                 1205
#define IDC_STATIC_READY_POS            1206
#define IDC_STATIC_PROCESS_POS          1207
#define IDC_STATIC_ALIGN_OFFSET         1208
#define IDC_STATIC_LIMIT_MIN            1209
#define IDC_STATIC_LIMIT_MAX            1210
#define IDC_STATIC_MANUAL_SPEED         1211
#define IDC_STATIC_PROCESS_SPEED        1212
#define IDC_STATIC_ROI_MIN              1213
#define IDC_STATIC_ROI_MAX              1214
#define IDC_GRP_UPPER                   1214
#define IDC_STATIC_UPPER                1215
#define IDC_GRP_SIDE                    1215
#define IDC_STATIC_PORT_1               1215
#define IDC_STATIC_SIDE                 1216
#define IDC_STATIC_BAUD_1               1216
#define IDC_STATIC_TEST_ROI_MAX         1216
#define IDC_STATIC_EDGE                 1217
#define IDC_STATIC_DATABIT_1            1217
#define IDC_STATIC_PARITY_1             1218
#define IDC_STATIC_STOPBIT_1            1219
#define IDC_STATIC_PORT_2               1220
#define IDC_STATIC_BAUD_2               1221
#define IDC_STATIC_DATABIT_2            1222
#define IDC_STATIC_PARITY_2             1223
#define IDC_STATIC_STOPBIT_2            1224
#define IDC_CMB_PORT_1                  1226
#define IDC_GRP_UPPER_LIGHT             1227
#define IDC_STATIC_PORT_3               1230
#define IDC_STATIC_BAUD_3               1231
#define IDC_CHK_MISSALIGN_X             1231
#define IDC_STATIC_DATABIT_3            1232
#define IDC_CHK_MISSALIGN_Y             1232
#define IDC_STATIC_PARITY_3             1233
#define IDC_CHK_OPEN                    1233
#define IDC_STATIC_STOPBIT_3            1234
#define IDC_CHK_SHORT                   1234
#define IDC_STATIC_PORT_4               1235
#define IDC_CHK_WIDTH                   1235
#define IDC_STATIC_BAUD_4               1236
#define IDC_CHK_HEIGHT                  1236
#define IDC_STATIC_DATABIT_4            1237
#define IDC_COLOR_MISSALIGN_X           1237
#define IDC_STATIC_PARITY_4             1238
#define IDC_COLOR_MISSALIGN_Y           1238
#define IDC_PIC_MANUAL_ALIGN            1238
#define IDC_STATIC_STOPBIT_4            1239
#define IDC_COLOR_OPEN                  1239
#define IDC_STATIC_OFFSET               1239
#define IDC_CMB_BAUD_1                  1240
#define IDC_COLOR_SHORT                 1240
#define IDC_STATIC_UPPER_ALIGN_OFFSET   1240
#define IDC_CMB_CAMERA                  1240
#define IDC_CMB_DATABIT_1               1241
#define IDC_COLOR_WIDTH                 1241
#define IDC_STATIC_SIDE_ALIGN_OFFSET    1241
#define IDC_STATIC_UPPER_X              1241
#define IDC_CMB_PARITY_1                1242
#define IDC_COLOR_HEIGHT                1242
#define IDC_STATIC_SPACE                1242
#define IDC_STATIC_UPPER_Y              1242
#define IDC_CMB_STOPBIT_1               1243
#define IDC_STATIC_UPPER_X_POS          1243
#define IDC_CMB_PORT_2                  1244
#define IDC_STATIC_UPPER_Y_POS          1244
#define IDC_CHK_BOTH                    1244
#define IDC_CMB_BAUD_2                  1245
#define IDC_STATIC_SIDE_X               1245
#define IDC_COLOR_BOTH                  1245
#define IDC_CMB_DATABIT_2               1246
#define IDC_STATIC_MAIN_X               1246
#define IDC_CHK_UPPER_MARK_1            1246
#define IDC_CMB_PARITY_2                1247
#define IDC_STATIC_SIDE_Y               1247
#define IDC_CHK_SIDE_MARK_1             1247
#define IDC_CMB_STOPBIT_2               1248
#define IDC_STATIC_MAIN_Y               1248
#define IDC_TREE_FOLDER                 1248
#define IDC_CMB_PORT_3                  1249
#define IDC_STATIC_SUB_X                1249
#define IDC_LIST_FOLDER                 1249
#define IDC_CHK_UPPER_MARK_2            1249
#define IDC_CMB_BAUD_3                  1250
#define IDC_PIC_SELECT                  1250
#define IDC_STATIC_SIDE_X_POS           1250
#define IDC_CHK_SIDE_MARK_2             1250
#define IDC_CMB_DATABIT_3               1251
#define IDC_STATIC_SIDE_Y_POS           1251
#define IDC_CMB_PARITY_3                1252
#define IDC_LIST_TOTAL                  1252
#define IDC_STATIC_MANUAL_X             1252
#define IDC_CMB_STOPBIT_3               1253
#define IDC_LIST_UPPER                  1253
#define IDC_STATIC_MANUAL_Y             1253
#define IDC_CMB_PORT_4                  1254
#define IDC_LIST_SIDE                   1254
#define IDC_STATIC_MANUAL_X_POS         1254
#define IDC_CMB_BAUD_4                  1255
#define IDC_PIC_RESULT                  1255
#define IDC_PIC_RESULT_UPPER            1255
#define IDC_STATIC_MANUAL_Y_POS         1255
#define IDC_CMB_DATABIT_4               1256
#define IDC_PIC_RESULT_SIDE             1256
#define IDC_CMB_PARITY_4                1257
#define IDC_BTN_EMO                     1257
#define IDC_CMB_STOPBIT_4               1258
#define IDC_GRP_SIDE_LIGHT              1259
#define IDC_LIST_ALARM                  1259
#define IDC_GRP_UPPER_AF                1260
#define IDC_LIST_LOG                    1260
#define IDC_GRP_SIDE_AF                 1261
#define IDC_EDIT_PROCESS                1261
#define IDC_PIC_FOCUS                   1262
#define IDC_EDIT_MORP_OPEN              1263
#define IDC_EDIT_MORP_CLOSE             1264
#define IDC_EDIT_BINARY                 1265
#define IDC_EDIT_CONTOUR                1266
#define IDC_BTN_MORP                    1267
#define IDC_BTN_BINARY                  1268
#define IDC_BTN_CONTOUR                 1269
#define IDC_BTN_FOCUS_RESET             1270
#define IDC_EDIT_TEST_ROI_MIN           1271
#define IDC_EDIT_TEST_ROI_MAX           1272
#define IDC_PIC_LOADING                 1273
#define IDC_STATIC_LOAD_RECIPE          1275
#define IDC_STATIC_POPUP                1278
#define IDC_STATIC_LOGIN                1279
#define IDC_STATIC_ID                   1280
#define IDC_CMB_AF_STEP                 1280
#define IDC_STATIC_PASSWORD             1281
#define IDC_EDIT_ID                     1282
#define IDC_EDIT_PASSWORD               1283
#define IDC_PIC_OVERLAY_UPPER           1284
#define IDC_PIC_OVERLAY_SIDE            1285
#define IDC_STATIC_COLOR_OPEN           1287
#define IDC_STATIC_COLOR_SHORT          1288
#define IDC_STATIC_COLOR_WIDTH          1289
#define IDC_STATIC_COLOR_HEIGHT         1290
#define IDC_STATIC_COLOR_BOTH           1291
#define IDC_STATIC_COLOR_OK             1292
#define IDC_STATIC_COLOR_MA             1293
#define IDC_LIST_SIDE_MARK              1294
#define IDC_PIC_MANUAL_UPPER            1297
#define IDC_PIC_MANUAL_SIDE             1298
#define IDC_STATIC_UPPER_MAGNI          1299
#define IDC_STATIC_SIDE_MAGNI           1300
#define IDC_CMB_MAGNI                   1304
#define IDC_GRP_AF                      1305
#define IDC_CHK_UPPER_AF                1306
#define IDC_CHK_SIDE_AF                 1307
#define IDC_GRP_LIGHT                   1308
#define IDC_BTN_AF                      1309
#define IDC_BTN_AOI_AF                  1310
#define IDC_EDIT_AOI                    1311
#define IDC_STATIC_UPPER_AF             1312
#define IDC_STATIC_SIDE_AF              1313
#define IDC_STATIC_TEST_ROI_MIN         1316
#define IDC_STATIC_CLAMP                1317
#define IDC_STATIC_GLASS_ID             1319
#define IDC_EDIT_GLASS_ID               1320
#define ID_BUTTON32771                  32771
#define ID_FILE                         32772
#define ID_FILE_SAVE32773               32773
#define ID_SAVE_UPPERCAMERA             32774
#define ID_SAVE_SIDECAMERA              32775
#define ID_SAVE_CAM                     32776
#define ID_FILE_LOAD                    32777
#define ID_FILE_EXIT                    32778
#define ID_EDIT                         32779
#define ID_EDIT_DRAW                    32780
#define ID_DISPLAY_LINE                 32781
#define ID_DISPLAY_TEXT                 32782
#define ID_TEXT_UPPER                   32783
#define ID_TEXT_SIDE                    32784
#define ID_LINE_CROSS                   32785
#define ID_TOOLS                        32786
#define ID_TOOLS_GRAPHIC                32787
#define ID_GRAPHIC_ACTIVE               32788
#define ID_GRAPHIC_LINE                 32789
#define ID_GRAPHIC_RECTANGLE            32790
#define ID_GRAPHIC_CIRCLE               32791
#define ID_GRAPHIC_EDGE                 32792
#define ID_GRAPHIC_EDGE32793            32793
#define ID_COMPORT                      32794
#define ID_COMPORT_CONNECT              32795
#define ID_SYSTEM                       32796
#define ID_SYSTEM_LOGIN                 32797
#define ID_HELP32798                    32798
#define ID_HELP_VERSION                 32799
#define ID_SAVE_CAM_UPPER               32800
#define ID_SAVE_CAM_SIDE                32801
#define ID_SAVE_ALL_CAM                 32802
#define ID_SAVE_CAM_ALL                 32803
#define ID_UPPER_LEFT                   32804
#define ID_UPPER_RIGHT                  32805
#define ID_UPPER_RIGHT32806             32806
#define ID_UPPER_RIGHT32807             32807
#define ID_SIDE_LEFT                    32808
#define ID_SIDE_LEFT32809               32809
#define ID_SIDE_RIGHT                   32810
#define ID_SIDE_RIGHT32811              32811
#define ID_UPPER_LEFT_UP                32812
#define ID_UPPER_LEFT_DOWN              32813
#define ID_UPPER_RIGHT_UP               32814
#define ID_UPPER_RIGHT_DOWN             32815
#define ID_SIDE_LEFT_UP                 32816
#define ID_SIDE_LEFT_DOWN               32817
#define ID_SIDE_RIGHT_UP                32818
#define ID_SIDE_RIGHT_DOWN              32819
#define ID_GRAPHIC_EDGE_2               32820

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        279
#define _APS_NEXT_COMMAND_VALUE         32821
#define _APS_NEXT_CONTROL_VALUE         1321
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
